#  **SECTION 2: NUMPY (The Mathematical Powerhouse)**


## 1. Array Creation Functions


In [2]:
import numpy as np
arr = np.array([1, 2, 3]) #NumPy array me convert

In [3]:
np.zeros((2, 3)) #2x3 matrix of 0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((2, 2)) #2x3 matrix of 1

array([[1., 1.],
       [1., 1.]])

In [5]:
np.arange(0, 10, 2) #createbthe list of element from 0 to 8 having difference 2

array([0, 2, 4, 6, 8])

In [6]:
np.linspace(0, 1, 5) #Equal interval values generate

array([0.  , 0.25, 0.5 , 0.75, 1.  ])


## 2. Reshaping & Structure


In [9]:
arr = np.array([1, 2, 3, 4])
arr2 = arr.reshape(2, 2) #reshape the array in 2 X 2 Format
arr2

array([[1, 2],
       [3, 4]])

In [10]:
arr2.shape #Get Array size (rows, columns)

(2, 2)


## 3. Mathematical Operations (Vectorization)


In [11]:
arr = np.array([10, 20, 30])

print(arr + 5)
print(arr * 2)

[15 25 35]
[20 40 60]


In [12]:
np.sum(arr) #Sum of all Elements

np.int64(60)

In [13]:
np.mean(arr) #Mean

np.float64(20.0)


## 4. Indexing & Slicing


In [14]:
arr = np.array([10, 20, 30, 40])

print(arr[0])     # First element
print(arr[1:3])   # Slice

10
[20 30]



## 5. Matrix Operations


In [15]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

print(a + b) #Addition

[[ 6  8]
 [10 12]]


In [17]:
print(a.T) #Transpose of matrix

[[1 3]
 [2 4]]


In [16]:
np.dot(a, b) #Matrix Multiplication

array([[19, 22],
       [43, 50]])

## What is Vectorization?

* Vectorization means performing operations on entire datasets at once instead of using loops.
* It allows speedup the calculation.
* In normal Python, loops process data element by element, which is slower.
* NumPy enables vectorization by applying operations directly on arrays.
* It is widely used in AI/ML for handling large datasets efficiently.
* Vectorization improves performance, reduces code complexity, and makes programs more readable.
